name: potato_timer
description: "土豆时钟 - 激励自己完成目标"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 阿里云一键登录
  ali_auth:
    path: flutter_ali_auth
  # 弹窗提示
  fluttertoast: ^9.0.0
  # HTTP 请求
  http: ^1.1.0
  # 加密（用于生成缓存文件名）
  crypto: ^3.0.3
  # 本地存储
  shared_preferences: ^2.2.2
  # 本地数据库
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  # 本地通知
  flutter_local_notifications: ^18.0.1
  # 时区处理
  timezone: ^0.9.2
  # 图片选择
  image_picker: ^1.0.7
  # 版本更新相关
  package_info_plus: ^8.0.0
  open_file: ^3.3.2
  # 国际化
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/icon_close.png
    - assets/return_btn.png
    - assets/return_btn_fill.png
    - assets/background_gif.gif
    - assets/background_gif1.gif
    - assets/background_gif2.gif
    - assets/background_image.jpeg
    - assets/background_video.mp4
